version: "3"
services:
  selenium-hub:
    image: selenium/hub:4.13.0
    ports:
      - "4444:4444"  # Exposes Selenium Hub port for communication
    networks:
      - grid

  chrome:
    image: selenium/node-chrome:4.13.0
    depends_on:
      - selenium-hub  # Waits for the hub to be ready before starting
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    volumes:
      - /dev/shm:/dev/shm  # Ensures enough shared memory for Chrome
    networks:
      - grid

  edge:
    image: selenium/node-edge:4.13.0
    depends_on:
      - selenium-hub  
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    volumes:
      - /dev/shm:/dev/shm  
    networks:
      - grid

networks:
  grid:
    driver: bridge  # Ensures the containers can communicate
